const HELP = {
  import: 'import  # 维护命令：从归档证据重建台账；日常任务不要运行',
  'migrate-jd': 'migrate-jd  # 维护命令：迁移旧 JD 结构；日常任务不要运行',
  'rehash-jd': 'rehash-jd  # 维护命令：重算 JD 哈希；日常任务不要运行',
  'project-score': 'project-score [--top=30]  # 离线项目交付粗筛（v7）：无到岗证据即可发送，remoteSuggestion/askInOpener 告诉你 review 怎么记、开场白要问什么',
  'send-plan': 'send-plan [--limit=N] [--dry-run] [--show-rejected=10]  # 离线把材料就绪队列固化为计划文件 data/plans/plan-*.json，每条重过发送门禁并绑定 JD/开场白哈希',
  dispatch: 'dispatch [--plan=data/plans/plan-*.json] [--dry-run|--status] [--max-failures=3]  # 按计划文件逐条发送：全部门禁+额度+节流照走，安全/额度/浏览器异常即停机，重跑同一文件续跑',
  'review-relax': 'review-relax [--apply] [--limit=50]  # 离线列出/放宽被误判 remote=fail 的无到岗岗位为 negotiable',
  validate: 'validate  # 离线检查台账结构、证据路径与送达证据，不访问 BOSS',
  'normalize-conversations': 'normalize-conversations  # 离线重算会话归属状态；历史消息不再形成待回复队列',
  doctor: 'doctor  # 统一离线诊断：依赖、文件、命令帮助、台账与自测；不访问 BOSS、不消耗额度',
  capabilities: 'capabilities  # 离线列出页面别名、真实路由、就绪证据、通用控件和业务边界',
  preflight: 'preflight [--full]  # 实时就绪、熔断、额度和岗位队列总览；默认不展开岗位 ID，不消耗额度',
  check: 'check  # 只读检查 9222 浏览器、登录态和安全页；不导航、不点击',
  'daily-options': 'daily-options [--resume=off|explicit|positive]  # 查看或记录今日自动简历策略',
  replies: 'replies  # 同步会话列表；按消息归属输出待判断、联系方式和系统回执',
  interactions: 'interactions  # 读取“谁看过我/对我感兴趣的”并更新高意向来源',
  'job-sources': 'job-sources  # 离线列出全部岗位入口、优先级、最近运行和可恢复进度',
  'next-work': 'next-work [--lane=auto|conversations|jobs|discover]  # 离线返回指定工作通道的最高优先动作、对象和下一条命令',
  'conversation-workbench': 'conversation-workbench <jobId> [--boss-id=<encryptBossId>] [--full]  # 离线汇总任意当前会话、职位/JD、简历策略、错岗提示和下一步',
  'job-workbench': 'job-workbench <jobId> [--full]  # 离线汇总单岗位阶段、阻塞、JD/审核/文案/会话与下一步',
  'review-audit': 'review-audit [--limit=20|--full]  # 离线找出审核证据与 JD 冲突、或已明确停止却仍在队列的岗位',
  'resume-candidates': 'resume-candidates [--limit=20|--full]  # 按今日策略列出附件候选、需实时检查和人工判断',
  favorites: 'favorites [--page=1] [--full]  # 从第1页开始可恢复的收藏快照；默认压缩输出，末页才替换完整快照',
  'favorites-next': 'favorites-next  # 收藏扫描只推进一页，并返回累计页数/岗位数和下一步',
  'favorite-status': 'favorite-status [--limit=20|--full]  # 离线汇总当前收藏的首次联系/继续沟通状态，默认压缩输出',
  'favorite-queue': 'favorite-queue [--limit=20|--full]  # 离线列出当前收藏中尚未首次联系的岗位，默认压缩输出',
  profiles: 'profiles  # 离线列出开场白岗位方向与关键词',
  recommendations: 'recommendations  # 读取无关键词职位页的当前期望推荐流第一批，并保留专用标签',
  'recommendations-next': 'recommendations-next  # 推荐流只执行一次下一页或一次瀑布加载，并单独计一页额度',
  'recommendations-close': 'recommendations-close  # 关闭推荐流专用标签并清理续页状态',
  search: 'search <关键词> [--sort=latest] [--profile=<方向>]  # 只采集第一页并保留专用标签，禁用 --pages 批量翻页',
  'search-next': 'search-next  # 对上次搜索只执行一次下一页或一次瀑布流加载，并单独计一页额度',
  'search-close': 'search-close  # 关闭上次搜索专用标签并清理续页状态',
  'harvest-current': 'harvest-current [--source="当前兼职推荐流"] [--tab=<tabId>]  # 收录当前已登录 BOSS 职位页已加载的真实岗位卡片；下滚后可重复执行',
  candidates: 'candidates [--profile=<方向>] [--source=<来源>] [--sort=complete] [--limit=20]  # 按信息完整度列待读 JD 候选',
  read: 'read <jobId|BOSS详情URL> --jd  # 在线读取真实 JD，一次一个岗位',
  jd: 'jd <jobId>  # 离线复看已存 JD，不占额度',
  review: 'review <jobId> --remote=pending|pass|negotiable|fail --remote-evidence="..." --pay=pending|pass|fail --pay-evidence="..." --risk=pending|pass|fail --risk-evidence="..." [--next=...]',
  'ai-opener': 'ai-opener <jobId> [--profile=<方向>] | ai-opener --batch [--limit=N] [--retry-failed]  # 离线生成并保存事实受限的开场白；--batch 给整个审核通过队列批量生成并统计门禁拒绝原因',
  'save-opener': 'save-opener <jobId> [--profile=<方向>]  # 从 MSG 环境变量保存宿主模型定制开场白',
  'discard-opener': 'discard-opener <jobId>  # 离线撤回开场白草稿并退出材料就绪队列',
  'ai-send': 'ai-send <jobId> [--profile=ai-agent|frontend|miniprogram|fullstack|product-qa|flexible-delivery] [--dry-run|--use-saved]  # 先 dry-run 核文案，再 use-saved 真实发送',
  send: 'send <jobId|BOSS详情URL>  # 从 MSG 环境变量真实发送；优先使用 ai-send 的受控流程',
  'verify-delivery': 'verify-delivery <jobId>  # 只读复核 delivery_unverified，禁止用它重发',
  company: 'company <公司名> [--status=...] [--evidence=...] [--url=...]  # 离线维护远程友好公司池',
  'company-jobs': 'company-jobs <公司名>  # 在线读取公司当前全部岗位入口',
  list: 'list [--queue=approved|send-ready|review] [--sort=complete] [--limit=20] [--grep=正则] [--source=来源] [--has-remote]',
  'browser-tabs': 'browser-tabs  # 只读列出标签的 focused/visibility/登录/安全状态与推荐工作标签',
  'browser-open': 'browser-open <页面别名|BOSS_URL> [--tab=<id>] [--full]  # 默认跟随当前活动工作标签；capabilities 查看全部直达别名',
  'browser-snapshot': 'browser-snapshot [--tab=<tabId>] [--full]  # 默认压缩语义快照',
  'browser-click': 'browser-click (--selector=<CSS>|--text="精确文字") [--dry-run] [--allow-action] [--expect-text=文字|--expect-selector=CSS|--expect-absent=CSS] [--full]  # 先干运行解析目标；危险动作需 allow-action，执行后可声明断言',
  'browser-fill': 'browser-fill (--selector=<CSS>|--text="字段标签或占位文字") [--dry-run] [--full]  # 语义字段必须唯一；dry-run 可不提供值',
  'browser-select': 'browser-select (--selector=<CSS>|--text="字段标题") --option="精确选项" [--dry-run] [--full]',
  'browser-scroll': 'browser-scroll [--selector=<CSS>] [--y=像素] [--direction=up|down]  # 页面或容器滚动',
  'browser-back': 'browser-back [--tab=<tabId>]  # 当前 BOSS 标签后退并返回语义快照',
  'browser-wait': 'browser-wait (--selector=<CSS>|--text="文字") [--timeout=15000]  # 等待真实页面元素',
  'browser-hover': 'browser-hover (--selector=<CSS>|--text="文字") [--index=0]  # 悬停并返回语义快照',
  'browser-key': 'browser-key <Enter|Escape|ArrowDown|...>  # 向当前活动元素发送单个按键',
  'browser-toggle': 'browser-toggle (--selector=<CSS>|--text="设置项") --state=on|off [--dry-run] [--full]  # dry-run 只回读，不点击',
  'conversation-open': 'conversation-open --job-id=<encryptJobId> --boss-id=<encryptBossId> [--full]  # 默认紧凑返回消息摘要/系统卡片',
  'conversation-reply': 'conversation-reply --job-id=<id> --boss-id=<id> # 仅在用户明确要求时发送指定正文，不追加话术',
  'resume-send': 'resume-send --job-id=<id> --boss-id=<id> (--resume="精确附件.pdf"|--auto) [--dry-run] [--full]  # dry-run 实时预演，不发送',
  profile: 'profile  # 等待简历业务区就绪并列出当前三份真实附件',
  'settings-status': 'settings-status  # 回读登录、安全页和自动招呼语开关',
  budget: 'budget  # 查看 24 小时滚动额度与突发窗口',
  unlock: 'unlock --reason="人工确认说明" [--force]  # 仅按强制停止规则人工解锁',
  'self-test': 'self-test  # 离线回归检查',
};

function help(topic = '') {
  if (topic && HELP[topic]) return console.log(`用法: node workflow/boss.js ${HELP[topic]}`);
  if (topic) return console.log(`暂无 ${topic} 的专用帮助。可用主题：${Object.keys(HELP).join('/')}`);
  console.log([
    'BOSS 裸 CDP 工作流：node workflow/boss.js help <命令>',
    '每日入口：preflight → ai-opener --batch → send-plan → dispatch → 补审 review 队列 → 必要时读 JD/搜索',
    '每日指标：发送数（preflight.sends）；回复由本人接管，不再统计回复率；读了多少 JD 不是指标',
    '高风险动作：先 dry-run/精确双 ID；验证码、code32/36/37、403 或对象不唯一立即停止',
    `帮助主题：${Object.keys(HELP).join('/')}`,
  ].join('\n'));
}

module.exports = { HELP, help };
